/*
 */
package Process;

/**
 *
 * @author mint
 */
public class BatcherJFrame extends javax.swing.JFrame {

    /**
     * Creates new form BatcherJFrame
     */
    public BatcherJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        originalFolderScrollpane = new javax.swing.JScrollPane();
        originalFolderTextPane = new javax.swing.JTextPane();
        processedFolderScrollpane = new javax.swing.JScrollPane();
        processedFolderTextPane = new javax.swing.JTextPane();
        originalFolderLabelTitel = new javax.swing.JLabel();
        ProcessedFolderLabelTitel = new javax.swing.JLabel();
        actionFolderAddressLabel = new javax.swing.JLabel();
        originalFolderAddressLabel = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        fileMenuItem = new javax.swing.JMenu();
        exitFileMenuItem = new javax.swing.JMenuItem();
        renameMenuItem = new javax.swing.JMenu();
        convertMenuItem = new javax.swing.JMenu();
        helpMenuItem = new javax.swing.JMenu();
        aboutHelpMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        originalFolderScrollpane.setViewportView(originalFolderTextPane);

        processedFolderScrollpane.setViewportView(processedFolderTextPane);

        originalFolderLabelTitel.setText("Original folder:");

        ProcessedFolderLabelTitel.setText("Processed folder:");

        actionFolderAddressLabel.setText("no folder");

        originalFolderAddressLabel.setText("no folder");

        menuBar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, java.awt.Color.gray, java.awt.Color.lightGray));

        fileMenuItem.setText("File");

        exitFileMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        exitFileMenuItem.setText("Exit");
        exitFileMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitFileMenuItemActionPerformed(evt);
            }
        });
        fileMenuItem.add(exitFileMenuItem);

        menuBar.add(fileMenuItem);

        renameMenuItem.setText("Rename");
        menuBar.add(renameMenuItem);

        convertMenuItem.setText("Convert");
        menuBar.add(convertMenuItem);

        helpMenuItem.setText("Help");

        aboutHelpMenuItem.setText("About");
        helpMenuItem.add(aboutHelpMenuItem);

        menuBar.add(helpMenuItem);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(originalFolderLabelTitel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(originalFolderAddressLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 296, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ProcessedFolderLabelTitel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(actionFolderAddressLabel))
                    .addComponent(originalFolderScrollpane, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(processedFolderScrollpane, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(434, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ProcessedFolderLabelTitel)
                            .addComponent(actionFolderAddressLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(originalFolderScrollpane, javax.swing.GroupLayout.PREFERRED_SIZE, 687, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(originalFolderLabelTitel)
                            .addComponent(originalFolderAddressLabel))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(24, Short.MAX_VALUE)
                    .addComponent(processedFolderScrollpane, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        actionFolderAddressLabel.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitFileMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitFileMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitFileMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BatcherJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BatcherJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BatcherJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BatcherJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BatcherJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ProcessedFolderLabelTitel;
    private javax.swing.JMenuItem aboutHelpMenuItem;
    private javax.swing.JLabel actionFolderAddressLabel;
    private javax.swing.JMenu convertMenuItem;
    private javax.swing.JMenuItem exitFileMenuItem;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JMenu fileMenuItem;
    private javax.swing.JMenu helpMenuItem;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JLabel originalFolderAddressLabel;
    private javax.swing.JLabel originalFolderLabelTitel;
    private javax.swing.JScrollPane originalFolderScrollpane;
    private javax.swing.JTextPane originalFolderTextPane;
    private javax.swing.JScrollPane processedFolderScrollpane;
    private javax.swing.JTextPane processedFolderTextPane;
    private javax.swing.JMenu renameMenuItem;
    // End of variables declaration//GEN-END:variables
}
